### ISSUE TITLE
Long term support?

### ISSUE THREAD

**Issue by nayrban** [gofabian/spring-boot-data-r2dbc-jooq#1]
Hello Fabian, hope you are great!,
I have spent a lot of time trying to get some answers about jooq + reactive programming, I have look into R2DBC, but since a have all my repositories running with jooq I dont want to change to R2DBC directly, so my question is do you have some plans in future about this library? Also is this library was deployed in some production env?

**Comment by gofabian** [comment]
Hi nayrban,

this project was created because I couldn't find any similar solution for the combination of R2DBC and JOOQ. It contains only basic functionality. That means SQL queries are created using the JOOQ DSL context, translated to the correct SQL dialect and executed using the R2DBC database client.

I do not use it in a production environment and there is no concrete roadmap. But if you have any idea to improve this library feel free to open an issue or a PR. I would like to add support to the missing JOOQ methods (see Readme) but I cannot guarantee anything.

I would appreciate any technical suggestions or discussions about this topic.

Fabian
